create table if not exists user_preference
(
    id                                  bigint not null generated by default as identity,
    theme                               text not null,
    language                            text not null,
    login_id                            bigint null,
    constraint pk_user_preference primary key(id),
    constraint fk_user_preference_login foreign key (login_id) references login (id) on delete cascade on update cascade,
    constraint uk_user_preference_login unique (login_id)
);
