create table if not exists audit_history
(
    id                                  bigint not null generated by default as identity,
    action                              char(1),
    table_name                          text not null,
    table_pk                            bigint not null,
    row_data                            jsonb not null,
    update_login_id                     bigint not null,
    update_timestamp                    timestamp with time zone not null,
    constraint pk_audit_history primary key (id)
);
